### ISSUE TITLE
Multiple recipients in Python 3

### ISSUE THREAD

**Issue by MathyV** [mike-charles/python-buffering-smtp-handler#2]
When you specify multiple recipients it does not work in Python 3. There's an example here on how to specify the recipients (not sure if it is compatible with Python 2)

https://docs.python.org/3/library/email.examples.html

**Comment by mikecharles** [comment]
It works for me. You should specify the recipient list as a list. For example:

```python
import logging
from buffering_smtp_handler import BufferingSMTPHandler

logging_format = '[ %(asctime)s | %(levelname)s | %(module)s ] %(message)s'
handler = BufferingSMTPHandler('localhost',
                               'myself@gmail.com',
                               ['friend1@gmail.com', 'friend2@gmail.com'],
                               'This is the subject!', 1000, logging_format)
handler.setLevel('ERROR')
logger.addHandler(handler)
```

**Comment by MathyV** [comment]
Thx, I was finally able to solve this. I tried a list before but it didn't work, tried again and now it works :-)
